{
 "title": "MainPlatform backend",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Backend requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{\r\n  namespace=\"mainplatform\",\r\n  service=\"backend\",\r\n  handler!=\"/metrics\"\r\n}[2m]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Backend latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_request_duration_highr_seconds_bucket{\r\n      namespace=\"mainplatform\",\r\n      service=\"backend\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "HTTP 5xx rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(rate(http_requests_total{\r\n    namespace=\"mainplatform\",\r\n    service=\"backend\",\r\n    status=~\"5..\"\r\n  }[5m])) or vector(0)\r\n)\r\n/\r\nclamp_min(\r\n  sum(rate(http_requests_total{\r\n    namespace=\"mainplatform\",\r\n    service=\"backend\"\r\n  }[5m])),\r\n  0.001\r\n)",
     "legendFormat": "HTTP 5xx error rate"
    }
   ]
  },
  {
   "title": "Healthy backend targets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"mainplatform\", service=\"backend\"})",
     "legendFormat": "Healthy backend replicas"
    }
   ]
  },
  {
   "title": "FastAPI stdout/stderr",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"mainplatform\", app=\"backend\"}"
    }
   ]
  }
 ]
}